# Project Information
site_name: Grip framework
site_url: https://grip-framework.github.io/docs
site_author: Grip framework and its contributors
site_description: Grip documentation (web framework for Crystal).

# Repository
repo_name: Grip Github
repo_url: https://github.com/grip-framework/grip
edit_uri: https://github.com/grip-framework/docs/tree/master/docs/

# Copyright
copyright: "Copyright &copy; Grip framework and its contributors 2020"

# Configuration
theme:
  name: material
  language: en

  palette:
    primary: white

  logo: https://github.com/grip-framework/medias/raw/master/grip_avatar.png
  favicon: https://github.com/grip-framework/medias/raw/master/grip_avatar.png

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/grip-framework/grip

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Introduction:
      - Prelude: "index.md"
      - Installation: "installation.md"
      - Getting Started: "getting_started.md"
  - Application: "application.md"
  - Context: "context.md"
  - Routing:
      - Basic routing: "basic_routing.md"
      - Intermediate routing: "intermediate_routing.md"
      - Advanced routing: "advanced_routing.md"
      - Scope: "scope.md"
      - Forward: "forward.md"
      - WebSocket routing: "web_socket_routing.md"
      - Available verbs: "verbs.md"
  - Runtime flags: "runtime_flags.md"
  - Middleware:
      - Pipe middleware: "pipe_middleware.md"
      - Raw middleware: "raw_middleware.md"
  - Error handling: "error_handling.md"
  - Swagger: "swagger.md"
  - SSL: "ssl.md"
  - Deployment: "deployment.md"
  - Testing: "testing.md"
